@echo off
echo Starting SmartDine Microservices...

echo Starting Identity API on port 5001...
start "Identity API" dotnet run --project SmartDine.Identity.API

echo Starting Menu API on port 5002...
start "Menu API" dotnet run --project SmartDine.Menu.API

echo Starting Order API on port 5003...
start "Order API" dotnet run --project SmartDine.Order.API

echo Starting Table API on port 5004...
start "Table API" dotnet run --project SmartDine.Table.API

echo Starting AI API on port 5005...
start "AI API" dotnet run --project SmartDine.AI.API

echo Starting Gateway on port 5000...
start "API Gateway" dotnet run --project SmartDine.Gateway

echo All services started!
pause
